package pkg_CLASES;
// Generated 04/07/2017 8:41:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaCurso generated by hbm2java
 */
public class CategoriaCurso  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombreCategoria;
     private Integer rangoEdadInicio;
     private Integer rangoEdadFin;
     private Set<Cursos> cursoses = new HashSet<Cursos>(0);

    public CategoriaCurso() {
    }

    public CategoriaCurso(String nombreCategoria, Integer rangoEdadInicio, Integer rangoEdadFin, Set<Cursos> cursoses) {
       this.nombreCategoria = nombreCategoria;
       this.rangoEdadInicio = rangoEdadInicio;
       this.rangoEdadFin = rangoEdadFin;
       this.cursoses = cursoses;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Integer getRangoEdadInicio() {
        return this.rangoEdadInicio;
    }
    
    public void setRangoEdadInicio(Integer rangoEdadInicio) {
        this.rangoEdadInicio = rangoEdadInicio;
    }
    public Integer getRangoEdadFin() {
        return this.rangoEdadFin;
    }
    
    public void setRangoEdadFin(Integer rangoEdadFin) {
        this.rangoEdadFin = rangoEdadFin;
    }
    public Set<Cursos> getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set<Cursos> cursoses) {
        this.cursoses = cursoses;
    }




}


