package pkg_CLASES;
// Generated 04/07/2017 8:41:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private Integer idEstudiante;
     private String ci;
     private String nombres;
     private String apellidos;
     private Date fechaNac;
     private String EMail;
     private String username;
     private String password;
     private Set<Matriculas> matriculases = new HashSet<Matriculas>(0);

    public Estudiantes() {
    }

	
    public Estudiantes(String ci, String nombres, String apellidos) {
        this.ci = ci;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Estudiantes(String ci, String nombres, String apellidos, Date fechaNac, String EMail, String username, String password, Set<Matriculas> matriculases) {
       this.ci = ci;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.fechaNac = fechaNac;
       this.EMail = EMail;
       this.username = username;
       this.password = password;
       this.matriculases = matriculases;
    }
   
    public Integer getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Matriculas> getMatriculases() {
        return this.matriculases;
    }
    
    public void setMatriculases(Set<Matriculas> matriculases) {
        this.matriculases = matriculases;
    }




}


