package pkg_CLASES;
// Generated 04/07/2017 8:41:22 by Hibernate Tools 4.3.1



/**
 * RegistroNotas generated by hbm2java
 */
public class RegistroNotas  implements java.io.Serializable {


     private Integer idRegistro;
     private Matriculas matriculas;
     private Double notaTest1;
     private Double notaTest2;
     private Double notaFinal;
     private String estado;

    public RegistroNotas() {
    }

	
    public RegistroNotas(Matriculas matriculas) {
        this.matriculas = matriculas;
    }
    public RegistroNotas(Matriculas matriculas, Double notaTest1, Double notaTest2, Double notaFinal, String estado) {
       this.matriculas = matriculas;
       this.notaTest1 = notaTest1;
       this.notaTest2 = notaTest2;
       this.notaFinal = notaFinal;
       this.estado = estado;
    }
   
    public Integer getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(Integer idRegistro) {
        this.idRegistro = idRegistro;
    }
    public Matriculas getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Matriculas matriculas) {
        this.matriculas = matriculas;
    }
    public Double getNotaTest1() {
        return this.notaTest1;
    }
    
    public void setNotaTest1(Double notaTest1) {
        this.notaTest1 = notaTest1;
    }
    public Double getNotaTest2() {
        return this.notaTest2;
    }
    
    public void setNotaTest2(Double notaTest2) {
        this.notaTest2 = notaTest2;
    }
    public Double getNotaFinal() {
        return this.notaFinal;
    }
    
    public void setNotaFinal(Double notaFinal) {
        this.notaFinal = notaFinal;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


