package pkg_CLASES;
// Generated 04/07/2017 8:41:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matriculas generated by hbm2java
 */
public class Matriculas  implements java.io.Serializable {


     private Integer idMatricula;
     private Cursos cursos;
     private Estudiantes estudiantes;
     private String estado;
     private Date fechaMat;
     private Set<RegistroNotas> registroNotases = new HashSet<RegistroNotas>(0);

    public Matriculas() {
    }

	
    public Matriculas(Cursos cursos, Estudiantes estudiantes) {
        this.cursos = cursos;
        this.estudiantes = estudiantes;
    }
    public Matriculas(Cursos cursos, Estudiantes estudiantes, String estado, Date fechaMat, Set<RegistroNotas> registroNotases) {
       this.cursos = cursos;
       this.estudiantes = estudiantes;
       this.estado = estado;
       this.fechaMat = fechaMat;
       this.registroNotases = registroNotases;
    }
   
    public Integer getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(Integer idMatricula) {
        this.idMatricula = idMatricula;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaMat() {
        return this.fechaMat;
    }
    
    public void setFechaMat(Date fechaMat) {
        this.fechaMat = fechaMat;
    }
    public Set<RegistroNotas> getRegistroNotases() {
        return this.registroNotases;
    }
    
    public void setRegistroNotases(Set<RegistroNotas> registroNotases) {
        this.registroNotases = registroNotases;
    }




}


