package pkg_CLASES;
// Generated 04/07/2017 8:41:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private Integer idPeriodo;
     private String nombrePeriodo;
     private Date fechaInicio;
     private Date fechaFin;
     private Set<Cursos> cursoses = new HashSet<Cursos>(0);

    public Periodo() {
    }

    public Periodo(String nombrePeriodo, Date fechaInicio, Date fechaFin, Set<Cursos> cursoses) {
       this.nombrePeriodo = nombrePeriodo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.cursoses = cursoses;
    }
   
    public Integer getIdPeriodo() {
        return this.idPeriodo;
    }
    
    public void setIdPeriodo(Integer idPeriodo) {
        this.idPeriodo = idPeriodo;
    }
    public String getNombrePeriodo() {
        return this.nombrePeriodo;
    }
    
    public void setNombrePeriodo(String nombrePeriodo) {
        this.nombrePeriodo = nombrePeriodo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set<Cursos> getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set<Cursos> cursoses) {
        this.cursoses = cursoses;
    }




}


