package pkg_CLASES;
// Generated 04/07/2017 8:41:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tutor generated by hbm2java
 */
public class Tutor  implements java.io.Serializable {


     private Integer idTutor;
     private String ciTutor;
     private String nombreTutor;
     private String apellidoTutor;
     private String EMail;
     private String titulo;
     private String username;
     private String password;
     private Set<Cursos> cursoses = new HashSet<Cursos>(0);

    public Tutor() {
    }

    public Tutor(String ciTutor, String nombreTutor, String apellidoTutor, String EMail, String titulo, String username, String password, Set<Cursos> cursoses) {
       this.ciTutor = ciTutor;
       this.nombreTutor = nombreTutor;
       this.apellidoTutor = apellidoTutor;
       this.EMail = EMail;
       this.titulo = titulo;
       this.username = username;
       this.password = password;
       this.cursoses = cursoses;
    }
   
    public Integer getIdTutor() {
        return this.idTutor;
    }
    
    public void setIdTutor(Integer idTutor) {
        this.idTutor = idTutor;
    }
    public String getCiTutor() {
        return this.ciTutor;
    }
    
    public void setCiTutor(String ciTutor) {
        this.ciTutor = ciTutor;
    }
    public String getNombreTutor() {
        return this.nombreTutor;
    }
    
    public void setNombreTutor(String nombreTutor) {
        this.nombreTutor = nombreTutor;
    }
    public String getApellidoTutor() {
        return this.apellidoTutor;
    }
    
    public void setApellidoTutor(String apellidoTutor) {
        this.apellidoTutor = apellidoTutor;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Cursos> getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set<Cursos> cursoses) {
        this.cursoses = cursoses;
    }




}


